[gcloud]
disabled=true

[kubernetes]
disabled=false
detect_files=["helmfile.yaml"]
detect_folders=["helm", "chart"]
# Not setting it would enable it always in v1.19.0: https://github.com/starship/starship/issues/5978
detect_env_vars = ['INVALID']

[docker_context]
disabled=true
